import { en, type Dict, type DictKey } from "./dict/en";

/**
 * Dictionaries are code-split. A citizen on a 2G connection downloads exactly
 * one language file, never twenty-three.
 *
 * Generated by scripts/gen-loader.mjs from the files actually present, because
 * Next resolves these imports at build time and a loader pointing at a missing
 * dictionary breaks the build rather than falling back.
 *
 * Every dictionary here is machine-translated from English and has not been
 * reviewed by a native speaker. That is stated in the picker rather than
 * implied away: a legal deadline rendered wrongly in Santali is worse than one
 * rendered in English next to an honest label. Any key missing from a
 * dictionary falls through to English rather than rendering blank.
 */
type PartialDict = Partial<Record<DictKey, string>>;

const LOADERS: Record<string, () => Promise<{ default: PartialDict }>> = {
  as: () => import("./dict/as").then((m) => ({ default: m.as })),
  bn: () => import("./dict/bn").then((m) => ({ default: m.bn })),
  brx: () => import("./dict/brx").then((m) => ({ default: m.brx })),
  doi: () => import("./dict/doi").then((m) => ({ default: m.doi })),
  gu: () => import("./dict/gu").then((m) => ({ default: m.gu })),
  hi: () => import("./dict/hi").then((m) => ({ default: m.hi })),
  kn: () => import("./dict/kn").then((m) => ({ default: m.kn })),
  kok: () => import("./dict/kok").then((m) => ({ default: m.kok })),
  ks: () => import("./dict/ks").then((m) => ({ default: m.ks })),
  mai: () => import("./dict/mai").then((m) => ({ default: m.mai })),
  ml: () => import("./dict/ml").then((m) => ({ default: m.ml })),
  mni: () => import("./dict/mni").then((m) => ({ default: m.mni })),
  mr: () => import("./dict/mr").then((m) => ({ default: m.mr })),
  ne: () => import("./dict/ne").then((m) => ({ default: m.ne })),
  or: () => import("./dict/or").then((m) => ({ default: m.or })),
  pa: () => import("./dict/pa").then((m) => ({ default: m.pa })),
  sa: () => import("./dict/sa").then((m) => ({ default: m.sa })),
  sat: () => import("./dict/sat").then((m) => ({ default: m.sat })),
  sd: () => import("./dict/sd").then((m) => ({ default: m.sd })),
  ta: () => import("./dict/ta").then((m) => ({ default: m.ta })),
  te: () => import("./dict/te").then((m) => ({ default: m.te })),
  ur: () => import("./dict/ur").then((m) => ({ default: m.ur })),
};

/** Proportion of the English keys each dictionary actually carries. */
export const COVERAGE: Record<string, number> = {
  en: 1,
  as: 0.470,
  bn: 0.587,
  brx: 0.586,
  doi: 0.587,
  gu: 0.400,
  hi: 0.589,
  kn: 0.444,
  kok: 0.587,
  ks: 0.586,
  mai: 0.586,
  ml: 0.433,
  mni: 0.589,
  mr: 0.589,
  ne: 0.589,
  or: 0.586,
  pa: 0.457,
  sa: 0.587,
  sat: 0.586,
  sd: 0.589,
  ta: 0.589,
  te: 0.309,
  ur: 0.390,
};

/** Languages with a dictionary. Everything else falls back to English. */
export const TRANSLATED = new Set(["en", ...Object.keys(LOADERS)]);

export function isTranslated(code: string): boolean {
  return TRANSLATED.has(code);
}

/** True for every language whose strings came out of a model, unreviewed. */
export function isMachineTranslated(code: string): boolean {
  return code !== "en" && TRANSLATED.has(code);
}

export function coverageOf(code: string): number {
  return COVERAGE[code] ?? 0;
}

const cache = new Map<string, Dict>();

export async function loadDict(code: string): Promise<Dict> {
  if (code === "en") return en as unknown as Dict;
  const hit = cache.get(code);
  if (hit) return hit;

  const load = LOADERS[code];
  if (!load) return en as unknown as Dict;

  try {
    const { default: partial } = await load();
    const merged = { ...(en as unknown as Dict), ...partial };
    cache.set(code, merged);
    return merged;
  } catch {
    return en as unknown as Dict;
  }
}
