/**
 * Rewrite loader.ts from whichever dictionaries actually exist on disk.
 *
 * Next resolves these dynamic imports at build time, so a loader pointing at a
 * file that is not there breaks the build. Generating the map from the
 * directory keeps the two from drifting apart.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DIR = resolve(ROOT, "src/lib/i18n/dict");

const codes = readdirSync(DIR)
  .filter((f) => f.endsWith(".ts") && f !== "en.ts")
  .map((f) => f.replace(/\.ts$/, ""))
  .sort();

const KEY = /^\s*"([A-Za-z0-9._]+)":/;
const count = (f) =>
  readFileSync(resolve(DIR, f), "utf8").split("\n").filter((l) => KEY.test(l)).length;
const total = count("en.ts");

const rows = codes.map((c) => `  ${c}: () => import("./dict/${c}").then((m) => ({ default: m.${c} })),`).join("\n");
const cov = codes
  .map((c) => `  ${c}: ${(count(`${c}.ts`) / total).toFixed(3)},`)
  .join("\n");

writeFileSync(
  resolve(ROOT, "src/lib/i18n/loader.ts"),
  `import { en, type Dict, type DictKey } from "./dict/en";

/**
 * Dictionaries are code-split. A citizen on a 2G connection downloads exactly
 * one language file, never twenty-three.
 *
 * Generated by scripts/gen-loader.mjs from the files actually present, because
 * Next resolves these imports at build time and a loader pointing at a missing
 * dictionary breaks the build rather than falling back.
 *
 * Every dictionary here is machine-translated from English and has not been
 * reviewed by a native speaker. That is stated in the picker rather than
 * implied away: a legal deadline rendered wrongly in Santali is worse than one
 * rendered in English next to an honest label. Any key missing from a
 * dictionary falls through to English rather than rendering blank.
 */
type PartialDict = Partial<Record<DictKey, string>>;

const LOADERS: Record<string, () => Promise<{ default: PartialDict }>> = {
${rows}
};

/** Proportion of the English keys each dictionary actually carries. */
export const COVERAGE: Record<string, number> = {
  en: 1,
${cov}
};

/** Languages with a dictionary. Everything else falls back to English. */
export const TRANSLATED = new Set(["en", ...Object.keys(LOADERS)]);

export function isTranslated(code: string): boolean {
  return TRANSLATED.has(code);
}

/** True for every language whose strings came out of a model, unreviewed. */
export function isMachineTranslated(code: string): boolean {
  return code !== "en" && TRANSLATED.has(code);
}

export function coverageOf(code: string): number {
  return COVERAGE[code] ?? 0;
}

const cache = new Map<string, Dict>();

export async function loadDict(code: string): Promise<Dict> {
  if (code === "en") return en as unknown as Dict;
  const hit = cache.get(code);
  if (hit) return hit;

  const load = LOADERS[code];
  if (!load) return en as unknown as Dict;

  try {
    const { default: partial } = await load();
    const merged = { ...(en as unknown as Dict), ...partial };
    cache.set(code, merged);
    return merged;
  } catch {
    return en as unknown as Dict;
  }
}
`,
);

console.log(`loader.ts: ${codes.length} dictionaries`);
for (const c of codes) console.log(`  ${c} ${Math.round((count(`${c}.ts`) / total) * 100)}%`);
